stages:
  - deployments

deployment_dev:
  stage: deployments
  trigger:
    include: .gitlab-ci.dev.yml
  rules:
    - if: $CI_COMMIT_BRANCH == 'development'

deployment_prod:
  stage: deployments
  trigger:
    include: .gitlab-ci.prod.yml
  rules:
    - if: $CI_COMMIT_BRANCH == 'production'