spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    eureka-server-port: 8761
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://ps-service-registry-production.up.railway.app/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: EFE97BCAB41D5933E6FCD19A99F97863E3126DEDEB2695DA369514E32D
    expiration:
      milisecons: 86400000

zuul:
  # ignored-services: '*'
  prefix: /v1
  routes:
    master:
      path: /master/**
      serviceId: master-service
      sensitiveHeaders: Cookie,Set-Cookie
    access:
      path: /access/**
      serviceId: access-management
      sensitiveHeaders: Cookie,Set-Cookie
    asdp:
      path: /data-core/**
      serviceId: asdp-data-collection-service
      sensitiveHeaders: Cookie,Set-Cookie
    mitra:
      path: /data-mitra/**
      serviceId: mitra-data-collection-service
      sensitiveHeaders: Cookie,Set-Cookie
    settlement-in:
      path: /settlement-in/**
      serviceId: settlement-in-service
      sensitiveHeaders: Cookie,Set-Cookie
    settlement-out:
      path: /settlement-out/**
      serviceId: settlement-out-service
      sensitiveHeaders: Cookie,Set-Cookie

server:
  port: 8760

ribbon:
  ReadTimeout: 600000
  connection-timeout: 30000
  eureka:
    enabled: true
